"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { Download, ImagePlus, LockKeyhole, Ruler } from "lucide-react";
import { mmToPixels, pixelsToMm, sanitizeFilename } from "@/lib/photo-core";

type Format="jpeg"|"png"|"webp";
export default function ResizePage(){
  const [url,setUrl]=useState<string|null>(null);const [name,setName]=useState("");const [source,setSource]=useState({width:0,height:0});const [width,setWidth]=useState(0);const [height,setHeight]=useState(0);const [dpi,setDpi]=useState(300);const [locked,setLocked]=useState(true);const [format,setFormat]=useState<Format>("jpeg");const [status,setStatus]=useState("请选择照片");const inputRef=useRef<HTMLInputElement>(null);const imageRef=useRef<HTMLImageElement>(null);
  const pick=(file?:File)=>{if(!file)return;if(!file.type.startsWith("image/")){setStatus("请选择图片文件");return}const next=URL.createObjectURL(file);setUrl(old=>{if(old)URL.revokeObjectURL(old);return next});setName(file.name);const image=new Image();image.onload=()=>{setSource({width:image.width,height:image.height});setWidth(image.width);setHeight(image.height);setStatus("已读取原始尺寸")};image.src=next};
  const setW=(next:number)=>{setWidth(next);if(locked&&source.width)setHeight(Math.max(1,Math.round(next/source.width*source.height)))};const setH=(next:number)=>{setHeight(next);if(locked&&source.height)setWidth(Math.max(1,Math.round(next/source.height*source.width)))};
  const save=()=>{const image=imageRef.current;if(!image||!width||!height){setStatus("请先选择照片并设置有效尺寸");return}const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.drawImage(image,0,0,width,height);canvas.toBlob(blob=>{if(!blob)return;const href=URL.createObjectURL(blob);const a=document.createElement("a");a.href=href;a.download=`${sanitizeFilename(name.replace(/\.[^.]+$/,""))}_${width}x${height}.${format==="jpeg"?"jpg":format}`;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);setStatus(`已导出 ${width} × ${height} px`)},`image/${format}`,.95)};
  return <main className="standalone-page"><header className="standalone-nav"><Link href="/">简照 SimplePortrait</Link><nav><Link href="/id-photo">证件照制作</Link><Link href="/tools">全部工具</Link></nav></header><section className="resize-workspace"><aside className="resize-intro"><i><Ruler size={24}/></i><span className="eyebrow">STANDALONE TOOL</span><h1>修改图片尺寸</h1><p>专门修改像素、实体尺寸和 DPI，不设置目标文件大小。</p><small><LockKeyhole size={14}/>照片仅在本机处理</small></aside><section className="resize-preview">{url?<img ref={imageRef} src={url} alt="待修改尺寸照片"/>:<button onClick={()=>inputRef.current?.click()}><ImagePlus size={32}/><b>选择照片</b><span>支持 JPG、PNG、WebP</span></button>}<input hidden ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>pick(e.target.files?.[0])}/></section><aside className="resize-controls"><h2>输出尺寸</h2><div className="source-meta"><span>原始尺寸</span><b>{source.width?`${source.width} × ${source.height} px`:"—"}</b></div><label className="switch-line"><input type="checkbox" checked={locked} onChange={e=>setLocked(e.target.checked)}/>保持原始比例</label><label className="field-label spaced">像素尺寸</label><div className="dimension-row"><label><span>宽度</span><input type="number" min="1" value={width||""} onChange={e=>setW(Number(e.target.value))}/></label><span className="times">×</span><label><span>高度</span><input type="number" min="1" value={height||""} onChange={e=>setH(Number(e.target.value))}/></label><span className="unit">PX</span></div><label className="field-label spaced">实体尺寸</label><div className="dimension-row"><label><span>宽度</span><input type="number" min=".1" step=".1" value={width?pixelsToMm(width,dpi).toFixed(1):""} onChange={e=>setW(mmToPixels(Number(e.target.value),dpi))}/></label><span className="times">×</span><label><span>高度</span><input type="number" min=".1" step=".1" value={height?pixelsToMm(height,dpi).toFixed(1):""} onChange={e=>setH(mmToPixels(Number(e.target.value),dpi))}/></label><span className="unit">MM</span></div><div className="resize-inline"><label>DPI<input type="number" min="72" max="1200" value={dpi} onChange={e=>setDpi(Number(e.target.value))}/></label><label>格式<select value={format} onChange={e=>setFormat(e.target.value as Format)}><option value="jpeg">JPG</option><option value="png">PNG</option><option value="webp">WebP</option></select></label></div><p className="compress-status">{status}</p><button className="export-button" onClick={save}><Download size={18}/>保存调整后的照片</button></aside></section></main>
}
